### ISSUE TITLE
افزودن فهرست قلم‌ها برای ابزار araste-get

### ISSUE THREAD

**Issue by ekm507** [ekm507/araste-fonts#2]
سلام!
پیشنهاد می‌کنم اسم همهٔ قلم‌های موجود در این مخزن را در یک فایل بگذاریم تا ابزار `araste-get` بتواند از آن برای دریافت فهرست قلم‌ها استفاده کند. پس از این می‌توانیم امکان فهرست‌کردن قلم‌های موجود در مخزن‌ها را هم به این ابزار اضافه کنیم.

فایل می‌تواند ساختاری ساده داشته باشد که شامل اسم قلم بعلاوهٔ توضیحات آن باشد.

**Comment by nimafanniasl** [comment]
ایده خوبیه، ولی اول باید اون مشکل ۴۰۴ که بهتون گفته بودم حل شه

**Comment by ekm507** [comment]
الان ابزار araste-get به‌روز شده و می‌تونه فهرست قلم‌های موجود در مخزن رو بارگیری کنه.
ولی هنوز فایلی نداریم که این فهرست داخلش باشه!

من موقتاً یک فایل مارک‌داون می‌سازم که عنوان هر قلم رو همراه با چند خط کامنت داخل قلم داشته باشه.
در آینده بهتره یک اسکریپت هم برای خودکارسازی این نوشته بشه تا با افزوده‌شدن قلم‌های جدید این فایل هم به‌روزرسانی بشه.

**Comment by nimafanniasl** [comment]
عالی

**Comment by ekm507** [comment]
هم فایل و هم اسکریپت افزوده شد.
این ایشو را می‌بندم. بعداً برای تغییرات می‌توانیم ایشوی جدید باز کنیم.

**Comment by nimafanniasl** [comment]
این list.md در واقع همون ساده شده Fonts.md هست دیگه!

**Comment by ekm507** [comment]
بله همون‌طور است. تفاوت‌های اصلی اینه که اولاً این تصویر نداره. می‌شه بعداً یک نمونهٔ اسکی از خروجی قلم رو در این فایل قرار داد. تفاوت دیگر این که این یکی خودکار ساخته می‌شه. در Fonts.md شما می‌تونید هر توضیحی که دوست دارید اضافه کنید ولی این‌جا ترجیح می‌دم خودکار باشه.
